### ISSUE TITLE
Portal has been released

### ISSUE THREAD

**Issue by MattBlissett** [gbif/hp-dissco-flanders#5]
Hi,

I noticed you made a release on GitHub: https://github.com/gbif/hp-dissco-flanders/releases/tag/1.0

Nothing much has happened, as there's not yet any domain configured for this site.  Do you know what domain you will use?  e.g. https://data.dissco-flanders.be/ or replacing https://dissco-flanders.be/.

Either way, the instructions for setting it up are here: https://github.com/gbif/hosted-portals/blob/main/getting-started/domain-name.md

Thanks,

**Comment by nikodm** [comment]
Hi MattBlisset,

Thanks for the info, we would like to use our custom domain [https://dissco-flanders.be/](url) for our portal.

I just made the necessary DNS changes with our domain provider as you describe here: [https://github.com/gbif/hosted-portals/blob/main/getting-started/domain-name.md ](url)
The A-record now points to the described ip and there is a CNAME pointing to 'hosted-portal.gbif.org'

Let me know if you still need further info.

Thanks a lot in advance!
Kind regards,Niko

**Comment by MattBlissett** [comment]
Hi Niko,

The site is now live, and all the DNS looks correct to me. Congratulations!
