### ISSUE TITLE
Images not showing in production 

### ISSUE THREAD

**Issue by mtrekels** [gbif/hp-dissco-flanders#6]
**Describe the bug**
After making a new release, the images are not showing on the production website

**To Reproduce**
Make a new release. Build is passing. Staging website looks fine, production website not showing the background images.

**Comment by MortenHofft** [comment]
your domain is defined here https://github.com/gbif/hp-dissco-flanders/blob/master/_config.yml#L29
That is used for images so that the image caching service knows where to get them.

there is also one for [staging](https://github.com/gbif/hp-dissco-flanders/blob/master/_config_staging.yml) and uat

**Comment by mtrekels** [comment]
Fixed in release 1.1.1
