### ISSUE TITLE
Add a list of publications to the DF website

### ISSUE THREAD

**Issue by mtrekels** [gbif/hp-dissco-flanders#8]
I would like to add an extra tab on the webpage containing this list of publications:

https://docs.google.com/document/d/1HiZ3j0N5elE2Jz2uWWLd4BgeXXEGj5L_9YzTR8DDyW0/edit?usp=sharing

**Comment by mtrekels** [comment]
Preferred name of tab: 'Project output'

**Comment by LauraAbr** [comment]
Hi @MattBlissett, I've added a tab called 'Project output' containing a list of publications. Do you think there's a better format or layout that could be used to display a long literature list? I couldn't find anything suitable. Thanks!
